### ISSUE TITLE
Post URL not working

### ISSUE THREAD

**Issue by shehangamage** [ThinhVu/InstaProxyServer#1]
http://localhost:8084/v1?url=https://www.instagram.com/p/CfRWS9SOotz/?__a=1

**response:**
responseBody for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005751735}}},"lid":"7113585450623962911"}

**Comment by ThinhVu** [comment]
Hi,

Look like you're using the InstaProxyServer v1 format. This API has been removed from Instagram a long time ago.

Using v2 instead.

Read more:
https://stackoverflow.com/questions/11796349/instagram-how-to-get-my-user-id-from-username/38342137#38342137
